version: "3.9"
services:
    server:
        build: .
        ports:
            - "5000:5000"
        environment: 
            - TOKEN_KEY
            - WEB_SERVER_URL
            - WEB_SERVER_PORT
    redis:
        image: "redis:6.2-alpine"
        ports:
            - "6379:6379"
