# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: [update_server, update_django, update_quoridor]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        git submodule update --init --remote -- edagames-server
        git config user.email eda5@eventbrite.com
        git config user.name EDA5
        git commit -am "Update EDAGames Server"
        git push origin main
